import {_electron as electron} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'MeetingLoopUITest-'));
const errors=[];
const app=await electron.launch({args:['--user-data-dir='+path.join(dir,'electron-profile'),'.'],cwd:process.cwd(),env:{...process.env,MEETING_LOOP_VAULT:dir},timeout:30000});
try{
 const page=await app.firstWindow();
 page.on('pageerror',e=>errors.push(e.message));
 page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text())});
 await page.getByRole('heading',{name:'Good things start with a conversation.'}).waitFor();
 await page.getByRole('button',{name:'Explore an example'}).click();
 await page.getByRole('heading',{name:'Design review · sample meeting',level:1}).waitFor();
 await page.getByRole('textbox',{name:'Personal meeting notes'}).fill('My personal note stays unchanged across AI generation.');
 await page.getByRole('button',{name:'Transcript',exact:false}).click();
 await page.getByText('I will draft the design report describing the local vault, consent, task approvals, and evidence-based project memory.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Notes',exact:true}).click();
 if(await page.getByRole('textbox',{name:'Personal meeting notes'}).inputValue()!=='My personal note stays unchanged across AI generation.')throw new Error('Manual notes did not persist');
 fs.mkdirSync('docs/screenshots',{recursive:true});
 await page.screenshot({path:'docs/screenshots/meeting.png'});
 await page.getByRole('button',{name:'Overview',exact:true}).click();
 await page.screenshot({path:'docs/screenshots/overview.png'});
 await page.getByRole('button',{name:'Action items',exact:false}).click();
 const tasks=await page.getByRole('button',{name:'Approve local draft',exact:true}).count();
 if(tasks!==2)throw new Error(`Expected two task review controls; found ${tasks}`);
 await page.getByRole('button',{name:'Approve local draft',exact:true}).first().click();
 await page.getByRole('button',{name:'Create draft',exact:true}).waitFor();
 await page.screenshot({path:'docs/screenshots/tasks.png'});
 await page.getByRole('button',{name:'Settings & connections',exact:true}).click();
 await page.getByRole('heading',{name:'Your loop. Your way.'}).waitFor();
 await page.getByRole('combobox',{name:'Appearance'}).selectOption('dark');
 await page.screenshot({path:'docs/screenshots/settings-dark.png'});
 await page.getByRole('combobox',{name:'Appearance'}).selectOption('light');
 await page.getByRole('textbox',{name:'Search meetings'}).fill('zero dollars');
 await page.getByRole('heading',{name:'Search results'}).waitFor();
 await page.getByRole('button',{name:'Clear',exact:true}).click();
 await page.getByRole('button',{name:'Open floating copilot'}).click();
 await new Promise(r=>setTimeout(r,300));
 if(app.windows().length!==2)throw new Error('Floating overlay did not open');
 const overlay=app.windows()[1];await overlay.getByRole('combobox',{name:'Meeting context'}).waitFor();
 await overlay.screenshot({path:'docs/screenshots/overlay.png'});
 await overlay.getByRole('button',{name:'Close floating panel'}).click();
 if(errors.length)throw new Error('Renderer errors: '+errors.join('\n'));
 const result={passed:true,checks:['desktop launch','synthetic example','manual notes persistence','transcript view','notes view','overview','task review and approval','settings','theme switch','local search','floating overlay'],rendererErrors:errors,at:new Date().toISOString(),vault:dir};
 fs.mkdirSync('docs/benchmarks',{recursive:true});fs.writeFileSync('docs/benchmarks/ui-smoke.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await app.close();}
